base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('index', views.index, name='index'),
]

consumer_care/urls.py
from django.urls import path
from . import views


app_name = 'consumer_care'

urlpatterns = [
    path('upload/', views.upload_file, name='upload'),
]

massive_creation/urls.py
from django.urls import path
from . import views


app_name = 'massive_creation'

urlpatterns = [
    path('upload/', views.upload_file, name='upload'),
]

osiviewer/urls.py
from django.urls import path
from . import views


app_name = 'osiviewer'

urlpatterns = [
    path('upload/', views.upload_file, name='upload'),
    path('run/', views.ov_run, name='run'),
    path('columns/', views.columns, name='columns'),
    path('next/', views.next, name='next'),
]

osiweb/urls.py
from django.contrib import admin
from django.urls import path
from user_aut.views import *
from base.views import *
from consumer_care.views import *
from massive_creation.views import *
from osiviewer.views import *
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('massive_creation', include('massive_creation.urls')),
    path('consumer_care', include('consumer_care.urls')),
    path('osiviewer', include('osiviewer.urls')),
    path('user_aut', include('user_aut.urls')),
    path('base', include('base.urls')),
    path('', user_login, name='user_login'),
    path('index/', index, name='index'),
    path('logout/', user_logout, name='logout'),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required
def index(request):
    return render(request, 'base/index.html')

templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Osiweb</title>
        <!-- CSS only -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    </head>
    <body>

           <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}"> <img src="{% static '/images/logo.png' %}" width="300"
     height="60"> </a></li>

                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                {% endif %}


            </div>
        </nav>

        <div class="container">

            {% block body_block %}
            <!--Anything else from other .html files goes in here!-->
            {% endblock %}
        </div>

    </body>
</html>

templates/base/index.html
{% extends 'base/base.html' %}
{% load static %}
    {% block body_block %}
        <h1>Welcome to Osiweb</h1>

        {% csrf_token %}

        <nav class="navbar navbar-light bg-light">
            <div class="navbar-nav">
                <li><a class="nav-item nav-link" href="{% url 'massive_creation:upload' %}">Massive Creation</a></li>
                <li><a class="nav-item nav-link" href="{% url 'consumer_care:upload' %}">Consumer Care</a></li>
                <li><a class="nav-item nav-link" href="{% url 'osiviewer:upload' %}">Osiviewer</a></li>
            </div>
        </nav>

    {% endblock %}